- name: Deploy Web Application
  hosts: servers
  vars_files:
    - "group_vars/db_webservers.yml"
  tasks:
    - name: Install python dependancies
      apt: name={{item}} state=present
      become: yes
      with_items:
        - python
        - python-setuptools
        - python-dev
        - build-essential
        - python-pip
        - python-mysqldb
    - include: tasks/db-deploy.yml
    - include: tasks/web-deploy.yml