- name: Install MySQL database
    apt: name={{item}} state=present
    become: yes
    with_items:
      - mysql-server
      - mysql-client

- name: Installed and start mysql as a service
    become: yes
    service: name=mysql state=started enabled=yes

- name: Create Application database
  become: yes
  mysql_db: name=employee_db state=present

- name: Create database user
  become: yes
  mysql_user: 
    name: db_user
    password: Passw0rd
    priv: '*.*:ALL'
    state: present
    host: '%'